"""Auto-generate Markdown documentation from an MCP server."""

import asyncio

from rich.console import Console

from .client import with_client

console = Console()


async def _inspect(client):
    tools = await client.list_tools()
    resources = []
    prompts = []
    try:
        resources = await client.list_resources()
    except Exception:
        pass
    try:
        prompts = await client.list_prompts()
    except Exception:
        pass
    return {
        "server_info": client.server_info,
        "tools": tools,
        "resources": resources,
        "prompts": prompts,
    }


def _generate_markdown(result):
    info = result["server_info"]
    tools = result["tools"]
    resources = result["resources"]
    prompts = result["prompts"]

    name = info.get("name", "MCP Server")
    lines = []
    lines.append(f"# {name}\n")

    summary_parts = []
    if tools:
        summary_parts.append(f"{len(tools)} tools")
    if resources:
        summary_parts.append(f"{len(resources)} resources")
    if prompts:
        summary_parts.append(f"{len(prompts)} prompts")
    if summary_parts:
        lines.append(f"> {' · '.join(summary_parts)}\n")

    if tools:
        lines.append("## Tools\n")
        for tool in tools:
            name = tool.get("name", "unknown")
            desc = tool.get("description", "")
            lines.append(f"### `{name}`\n")
            if desc:
                lines.append(f"{desc}\n")

            schema = tool.get("inputSchema", {})
            props = schema.get("properties", {})
            required = schema.get("required", [])

            if props:
                lines.append(
                    "| Parameter | Type | Required | Description |"
                )
                lines.append("|-----------|------|----------|-------------|")
                for pname, pschema in props.items():
                    ptype = pschema.get("type", "any")
                    req = "Yes" if pname in required else "No"
                    pdesc = pschema.get("description", "\u2014")
                    lines.append(f"| `{pname}` | `{ptype}` | {req} | {pdesc} |")
                lines.append("")

    if resources:
        lines.append("## Resources\n")
        for res in resources:
            uri = res.get("uri", "")
            rname = res.get("name", "")
            rdesc = res.get("description", "")
            mime = res.get("mimeType", "")

            lines.append(f"### `{uri}`\n")
            if rdesc:
                lines.append(f"{rdesc}\n")
            meta = []
            if rname:
                meta.append(f"**Name:** {rname}")
            if mime:
                meta.append(f"**MIME Type:** `{mime}`")
            if meta:
                lines.append(" · ".join(meta) + "\n")

    if prompts:
        lines.append("## Prompts\n")
        for prompt in prompts:
            pname = prompt.get("name", "unknown")
            pdesc = prompt.get("description", "")
            args = prompt.get("arguments", [])

            lines.append(f"### `{pname}`\n")
            if pdesc:
                lines.append(f"{pdesc}\n")

            if args:
                lines.append("| Argument | Required | Description |")
                lines.append("|----------|----------|-------------|")
                for arg in args:
                    aname = arg.get("name", "?")
                    req = "Yes" if arg.get("required") else "No"
                    adesc = arg.get("description", "\u2014")
                    lines.append(f"| `{aname}` | {req} | {adesc} |")
                lines.append("")

    lines.append("---\n")
    lines.append("*Generated by [mcptools](https://github.com/Pavankumardhruv/mcptools)*\n")

    return "\n".join(lines)


def run_docs(server: str, output: str = None):
    result = asyncio.run(with_client(server, _inspect))
    markdown = _generate_markdown(result)

    if output:
        with open(output, "w") as f:
            f.write(markdown)
        console.print(f"[green]Wrote[/] {output}")
    else:
        print(markdown)
